version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install --upgrade pip setuptools wheel
    post_build:
      - rm -rf _build/html/_sources

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
      options:
        --no-deps
        --no-cache-dir

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub

